🐛 FIX: Corriger erreur vue récursive dans auth_responsive_override.xml
ERREUR CORRIGÉE:
ParseError: You cannot create recursive inherited views
Ligne 13: id='web.login_layout' inherit_id='web.login_layout'

CAUSE:
Template utilisait le même ID que le parent, créant une vue récursive

SOLUTION:
Changé id de 'web.login_layout' à 'onedesk_core.login_layout_responsive'

Maintenant le template hérite correctement de web.login_layout sans récursion.